In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[ 0.0000e+00, -4.6566e-10,  0.0000e+00],
        [-4.6566e-10,  5.6052e-45,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00, -4.6566e-10,  3.0631e-37]])


In [3]:
x = torch.rand(5, 3)

In [4]:
print(x)

tensor([[0.5407, 0.6190, 0.2821],
        [0.3812, 0.2828, 0.8648],
        [0.2801, 0.0280, 0.3265],
        [0.5458, 0.1642, 0.9528],
        [0.9261, 0.0057, 0.8354]])


In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [7]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [8]:
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[ 1.0806, -0.7541, -0.5422],
        [ 1.1770, -0.0059,  1.3205],
        [ 0.3291, -1.2129,  0.6714],
        [ 0.1204, -1.0104,  0.4344],
        [-0.5686, -0.5945,  0.1520]])


In [9]:
print(x.size())

torch.Size([5, 3])


In [10]:
x = torch.rand(5, 4)
y = torch.rand(5, 4)

In [11]:
x

tensor([[0.0578, 0.6185, 0.0875, 0.9709],
        [0.9448, 0.0082, 0.3156, 0.9935],
        [0.5153, 0.7189, 0.0762, 0.7467],
        [0.0884, 0.8314, 0.5579, 0.0216],
        [0.1844, 0.8919, 0.1458, 0.2044]])

In [12]:
x + y

tensor([[1.0470, 1.4434, 0.8378, 1.6713],
        [1.5521, 0.0410, 0.7687, 1.2818],
        [0.7690, 1.1702, 0.5260, 0.7678],
        [0.3130, 1.3864, 0.9457, 0.7433],
        [0.7315, 1.8202, 0.3958, 0.6257]])

In [13]:
z = torch.add(x, y)

In [14]:
z

tensor([[1.0470, 1.4434, 0.8378, 1.6713],
        [1.5521, 0.0410, 0.7687, 1.2818],
        [0.7690, 1.1702, 0.5260, 0.7678],
        [0.3130, 1.3864, 0.9457, 0.7433],
        [0.7315, 1.8202, 0.3958, 0.6257]])

In [15]:
y.add_(x)

tensor([[1.0470, 1.4434, 0.8378, 1.6713],
        [1.5521, 0.0410, 0.7687, 1.2818],
        [0.7690, 1.1702, 0.5260, 0.7678],
        [0.3130, 1.3864, 0.9457, 0.7433],
        [0.7315, 1.8202, 0.3958, 0.6257]])

In [16]:
y

tensor([[1.0470, 1.4434, 0.8378, 1.6713],
        [1.5521, 0.0410, 0.7687, 1.2818],
        [0.7690, 1.1702, 0.5260, 0.7678],
        [0.3130, 1.3864, 0.9457, 0.7433],
        [0.7315, 1.8202, 0.3958, 0.6257]])

In [17]:
x.t()

tensor([[0.0578, 0.9448, 0.5153, 0.0884, 0.1844],
        [0.6185, 0.0082, 0.7189, 0.8314, 0.8919],
        [0.0875, 0.3156, 0.0762, 0.5579, 0.1458],
        [0.9709, 0.9935, 0.7467, 0.0216, 0.2044]])

In [18]:
x.t_()

tensor([[0.0578, 0.9448, 0.5153, 0.0884, 0.1844],
        [0.6185, 0.0082, 0.7189, 0.8314, 0.8919],
        [0.0875, 0.3156, 0.0762, 0.5579, 0.1458],
        [0.9709, 0.9935, 0.7467, 0.0216, 0.2044]])

In [19]:
print(x[:, 1])

tensor([0.9448, 0.0082, 0.3156, 0.9935])


In [20]:
print(x.view(16))

RuntimeError: shape '[16]' is invalid for input of size 20

In [21]:
x = torch.randn(4, 4)
y = x.view(16)
print(y)

tensor([ 0.9098,  0.5738,  0.0131,  1.3235,  0.1899,  0.5014,  0.4624,  1.1085,
        -0.2516,  0.3114,  0.7604,  1.0008,  0.7830, -0.4360,  0.7620, -1.3558])


In [23]:
z = x.view(-1, 8)
print(z)

tensor([[ 0.9098,  0.5738,  0.0131,  1.3235,  0.1899,  0.5014,  0.4624,  1.1085],
        [-0.2516,  0.3114,  0.7604,  1.0008,  0.7830, -0.4360,  0.7620, -1.3558]])


In [25]:
x = torch.randn(1)

In [26]:
print(x.item())

-2.0240039825439453


In [27]:
print(x)

tensor([-2.0240])


In [28]:
a = torch.ones(5)

In [29]:
print(a)

tensor([1., 1., 1., 1., 1.])


In [30]:
b = a.numpy()

In [31]:
print(b)

[1. 1. 1. 1. 1.]


In [32]:
a.add_(1)

tensor([2., 2., 2., 2., 2.])

In [33]:
print(b)

[2. 2. 2. 2. 2.]


In [35]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
